[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "frontend"
  command = "echo 'No build needed for static site'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "20"
